Feature/at 5944 flask debug toolbar
dod-ccpo/atat pull request #2086
Opened 2021-02-03 16:02 UTC by jGonzalez-CCPO

https://ccpo.atlassian.net/browse/AT-5944

2021-02-03 16:12 UTC, nkingsley-ccpo commented
@jGonzalez-CCPO, I would recommend that we have a separate app.py for this (e.g. app-debug.py) and update the Procfile to use that instead, so we don't have a bleed-over of this that could propagate into prod.

2021-02-03 16:14 UTC, nkingsley-ccpo commented
Also, flask_debugtoolbar needs to be added as a python dev dependency

2021-02-03 17:42 UTC, jGonzalez-CCPO commented
> @jGonzalez-CCPO, I would recommend that we have a separate app.py for this (e.g. app-debug.py) and update the Procfile to use that instead, so we don't have a bleed-over of this that could propagate into prod.

done

2021-02-04 02:00 UTC, kylelaker-ccpo requested changes
Could you provide some context on why so many changes are being made to the `yarn.lock` file? It seems like all of the `integrity` lines with the SHA hashes are being removed which doesn't seem ideal.

2021-02-04 02:00 UTC, kylelaker-ccpo commented on atat/app.py
> +
Let's break out these names to make them slightly less "magic". Or use a regex and accept any environment that starts with `dev`.

```suggestion
    dev_env_names = ("dev", "development")
    if (ENV in dev_env_names) and app.config["DEV_DEBUG_TOOL"] == "True":
        debug_tools_bar(app)

```

2021-02-04 02:00 UTC, kylelaker-ccpo commented on atst2.code-workspace
> -		"workbench.colorTheme": "Visual Studio Light"
This modification will impact all other developers on the project using VS Code. It may be best to not commit any changes to this file. I think #2090 actually deletes this file.

2021-02-04 02:00 UTC, kylelaker-ccpo commented on config/base.ini
> +AZURE_USER_OBJECT_ID
Removing the EOL at the end of this file is likely a mistake of the text editor or IDE. Please restore the newline.

2021-02-04 14:38 UTC, jGonzalez-CCPO commented on atat/debug.py
> +        app.config["DEV_DEBUG_TOOL_SECRET_KEY"] or "jfhdfjshkjskjdjdhhe"
thanks. 

so, we don't need this step then.

2021-02-04 16:16 UTC, jGonzalez-CCPO commented on atst2.code-workspace
> -		"workbench.colorTheme": "Visual Studio Light"
Agree. I would reverse this.

2021-02-04 16:17 UTC, jGonzalez-CCPO commented on atat/app.py
> +
The standard name for the environment for development by the documentation of Flask should be `development.` 

But for some reason, everywhere in the code, the old team uses `dev.` 

I am trying to have a working theory of why they name this in a custom matter. At this moment, I don't know why. But if you can give me some inside about that, maybe in the ticket. 

> base on https://flask.palletsprojects.com/en/1.1.x/cli/#watch-extra-files-with-the-reloader

So, for me would be better to only have it on `development` (that exact word only), but if you read in the code there are some service been provided for the `dev` (also an exact word), so I try to make available for both.  

I am also open to plan this better with you later, probably a 15 min meeting.

2021-02-04 16:36 UTC, kylelaker-ccpo commented on atat/app.py
> +
Yep! I see that the goal is to make it work for both `dev` and `development` as the code is written; this small refactoring would accomplish the same thing but actually assign a "name" to those strings.

I feel we should have a discussion as part of a separate ticket whether we can use `development` instead of `dev`.

2021-02-04 18:59 UTC, jGonzalez-CCPO commented on atst2.code-workspace
> -		"workbench.colorTheme": "Visual Studio Light"
done

2021-02-05 21:02 UTC, kylelaker-ccpo reviewed
Couple recommendations on renaming as well in addition to moving this to a dev dependency

2021-02-08 18:31 UTC, jGonzalez-CCPO commented on atat/debug.py
> +def debug_tools_bar(app):
done

2021-02-08 18:58 UTC, jGonzalez-CCPO commented on atat/app.py
> +from atat.debug import debug_tools_bar
done

2021-02-08 18:58 UTC, jGonzalez-CCPO commented on atat/debug.py
> +def debug_tools_bar(app):
done

2021-02-08 22:30 UTC, jGonzalez-CCPO commented
METADATA FIX RE-BASE on https://github.com/dod-ccpo/atat/pull/2110

2021-02-08 22:30 UTC, closed without merging