Add flow control logs on NSG
dod-ccpo/atat pull request #2146
Opened 2021-02-19 15:00 UTC by kylelaker-ccpo

This is the work from the branch `AT-5711-NSG-flow-logs` rebased on the current `develop` branch. Additionally, the comments and information from #2004 provide some additional context.

Ticket: AT-5711

2021-02-19 16:54 UTC, jasonburkert-ccpo commented
> This is the work from the branch `AT-5711-NSG-flow-logs` rebased on the current `develop` branch.

@kylelaker-ccpo Should we keep that old branch until this one gets merged?

2021-02-19 17:01 UTC, kylelaker-ccpo commented
That would be my preference; I'll put a note on the ticket to mention the need to cleanup all related & unmerged branches once the PR is integrated

2021-03-18 00:44 UTC, kylelaker-ccpo commented
The bulk of the work here is as done as it will be at this point; however, I am going to keep the PR in draft status until I have the chance to rebase and squash some of these commits.

2021-03-18 01:49 UTC, jeffsegal-ccpo requested changes

2021-03-18 01:49 UTC, jeffsegal-ccpo commented on terraform/providers/application_env/k8s.tf
> +  address_prefixes = ["10.1.5.0/24"]
Can you use 10.1.6.0/24 instead? I already claimed 5 for the AG. :)

2021-03-18 01:54 UTC, kylelaker-ccpo commented on terraform/providers/application_env/k8s.tf
> +  address_prefixes = ["10.1.5.0/24"]
Done! I had a thought I should have just picked some other number further away just in case 6 was taken 😂

2021-03-18 02:35 UTC, jeffsegal-ccpo approved these changes

2021-03-18 02:35 UTC, merged