At 5578 xss attack validate name for dev new user
dod-ccpo/atat pull request #2194
Opened 2021-03-05 04:13 UTC by jGonzalez-CCPO

https://ccpo.atlassian.net/browse/AT-5578

2021-03-05 14:42 UTC, kylelaker-ccpo requested changes
Nice! Validating these inputs is going to be really great for the local dev environment. I have a changes to request though. Nice comments to explain the validation process.

2021-03-05 14:42 UTC, kylelaker-ccpo commented on atat/routes/dev.py
> +    class Struct(object):
Was there a specific reason to create a `Struct` class over using the standard library--provided `types.SimpleNamespace`? It works almost exactly the same way as what has been done here.

2021-03-05 14:42 UTC, kylelaker-ccpo commented on atat/routes/dev.py
> +    is_number({}, Struct(**{"data": dod_id}))
The `entries` parameter for `Struct.__init__` already has `**` so doing this on both ends makes the code harder to understand. The symbols are confusing so maybe consider:

```suggestion
    is_name({}, Struct(data=first_name))
    is_name({}, Struct(data=last_name))
    is_number({}, Struct(data=dod_id))
```

2021-03-05 14:42 UTC, kylelaker-ccpo commented on atat/routes/dev.py
> +    dod_id = request.args.get("dod_id", None, type=str)
Unless I am mistaken, URL query parameters are always going to be strings. Further, `None` is the default value for the `default` parameter. So the equivalent code is
```suggestion
    first_name = request.args.get("first_name")
    last_name = request.args.get("last_name")
    dod_id = request.args.get("dod_id")
```

2021-03-05 16:34 UTC, kylelaker-ccpo approved these changes
Looks good to me. Since we did some pair programming on parts of this, I would like to get @jasonburkert-ccpo to review as well. Locally validated the same test cases used in the Jira ticket.

2021-03-08 21:28 UTC, jasonburkert-ccpo approved these changes
Good back and forth with @kylelaker-ccpo

2021-03-08 21:43 UTC, merged