AT-6063 Standardize environment naming conventions
dod-ccpo/atat pull request #2203
Opened 2021-03-15 17:51 UTC by jGonzalez-CCPO

https://ccpo.atlassian.net/browse/AT-6063?focusedCommentId=310980

2021-03-15 20:49 UTC, jasonburkert-ccpo commented on README.md
> +2. If FLASK_ENV is set as an environment variable and there is an INI file with a matching name, that INI file is read in and applied. For instance, if FLASK_ENV is set to "production" and a "prod.in
@jGonzalez-CCPO In the case of setting FLASK_ENV="production", wouldn't the file that we look for be called `production.ini` ?

2021-03-15 20:49 UTC, jasonburkert-ccpo commented on terraform/providers/bootstrap/variables.tf
> +  # default     = "development"
This appears to be a comment.  Is it accurate after changing?  Should it be removed instead?

2021-03-15 20:49 UTC, jasonburkert-ccpo commented on README.md
> +2. If FLASK_ENV is set as an environment variable and there is an INI file with a matching name, that INI file is read in and applied. For instance, if FLASK_ENV is set to "production" and a "prod.in
In the case of FLASK_ENV="production", wouldn't the the expected file be `production.ini` ?

2021-03-15 21:42 UTC, jasonburkert-ccpo requested changes
Please review my comments.
Is this the intended functionality?

This looks good.
![image](https://user-images.githubusercontent.com/77642966/111224425-d4755980-85b4-11eb-92d2-52f87b6bc034.png)

This looks good.
![image](https://user-images.githubusercontent.com/77642966/111224439-d9d2a400-85b4-11eb-8fe4-acfa11a140d3.png)

Should this be more explicit about defaulting to "development"?  Is that, in fact, what has happened?

If FLASK_ENV is not production or development, I suggest some output, perhaps WARNING-level output, that says value 'foobar' was found for FLASK_ENV and you are defaulting to "development".  Then output "Environment: foobar" (in screenshot below), should instead say "Environment: development".

![image](https://user-images.githubusercontent.com/77642966/111224457-ddfec180-85b4-11eb-9274-91285da6fc78.png)

2021-03-15 21:42 UTC, jasonburkert-ccpo commented on atat/app.py
> +        g.dev = os.getenv("FLASK_ENV", "development") == "development"
Should this be conditional be `!= "production"` ?

2021-03-16 14:48 UTC, jGonzalez-CCPO commented on terraform/providers/bootstrap/variables.tf
> +  # default     = "development"
It is a piece of documentation for reference on the terrace template.

2021-03-16 14:51 UTC, jGonzalez-CCPO commented on README.md
> +2. If FLASK_ENV is set as an environment variable and there is an INI file with a matching name, that INI file is read in and applied. For instance, if FLASK_ENV is set to "production" and a "prod.in
I am not sure that functionality even exists in the current code. I have not used, or see any indication of a prod.ini file been called, or used. I can be wrong but looks to me that this one is out of the scope of the ticket.

2021-03-17 18:07 UTC, kylelaker-ccpo commented on atat/app.py
> +print(">>> Environment name set: %s", (str(ENV)))
This particular line has a few concerning things:
1. It prints directly to standard output without using the logging framework (as all our other messages do)
2. It will run _every time_ this file gets `import`ed which isn't ideal
3. As written, the `%` gets printed every time.

Can this move in to `make_app` _after_ `app` has been initalized? (Currently, that'd be Line 62)

So then the line would be:

```python
app.logger.info("Environment name set: %s", ENV)
```

`print` uses different semantics than the functions in the `logging` module and does not perform `%`-style interpolation. Additionally, all our output to the console should happen via the app logger.

2021-03-17 18:14 UTC, kylelaker-ccpo commented on atat/app.py
> +if not (ENV in ["development", "production", "test", "ci"]):
I would really prefer if our allowed values were defined as an `enum.Enum` rather than "magic strings".

```python
class ApplicationEnvironment(enum.Enum):
    DEVELOPMENT = "development"
    TEST = "test"
    CI = "ci"
    PRODUCTION = "production"

ENV = ApplicationEnvironment(os.getenv("FLASK_ENV", "development"))
```

And then everywhere, we can compare to `ApplicationEnvironment.DEVELOPMENT` or `ApplicationEnvironment.PRODUCTION` or something like that.

We'd even be able to define methods or attributes as well which may be nice. But in general, if we want to enumerate allowed values, we should use an enumeration :)

2021-03-17 20:55 UTC, jGonzalez-CCPO reviewed
changed

2021-03-17 20:55 UTC, jGonzalez-CCPO commented on atat/app.py
> +print(">>> Environment name set: %s", (str(ENV)))
@jasonburkert-ccpo agree to remove that log

2021-03-17 21:57 UTC, jGonzalez-CCPO commented on atat/app.py
> +if not (ENV in ["development", "production", "test", "ci"]):
@kylelaker-ccpo SO, if I get this well do you want this to fail instead of having a default ENV?

2021-03-17 21:57 UTC, jGonzalez-CCPO commented on atat/app.py
> +if not (ENV in ["development", "production", "test", "ci"]):
the criteria until now are to default to production

2021-03-17 22:30 UTC, jGonzalez-CCPO commented on atat/app.py
> +if not (ENV in ["development", "production", "test", "ci"]):
suggested changes 104 failed, 703 passed, 35 skipped, 1 warning in 51.70s

2021-03-18 01:47 UTC, jeffsegal-ccpo commented on atat/app.py
> +if not (ENV in ["development", "production", "test", "ci"]):
Hey guys - yes please always fail fast on things like this. Definitely never ever want to default to dev because that becomes a security risk.

2021-03-18 03:26 UTC, kylelaker-ccpo commented on atat/app.py
> +if not (ENV in ["development", "production", "test", "ci"]):
I hold the following fairly strong opinions related to the questions raised here:

1. It is important to always fail as early and descriptively as possible. We don't necessarily know what breaks or bad (and insecure) assumptions could be made in an "invalid" environment. We should fail quickly upfront. We should let users (users means "operators" and "developers" here) know _why_ there was a failure, even if it's implicit log messages
2. Enumerations provide additional safety, easier comparisons, and greater flexibility. You also get a usable error if you try to use an invalid value.

In addition to updating the initialization of `ENV`, it is important to replace all other uses of any of the literal strings with the `Enum` name. My suggestion here cannot be applied in isolation; it is the beginnings of a larger suggestion to "use an enum." If that will require further discussion and conversation, reach out and perhaps we can do a pair programming session or quick chat on this!

2021-03-18 18:44 UTC, jGonzalez-CCPO reviewed
In order to comply with the coverage requirement for testing, I finish rewriting the atat/app.py implementation of the environment name and the uses.

2021-03-18 18:44 UTC, jGonzalez-CCPO commented on atat/app.py
> +if not (ENV in ["development", "production", "test", "ci"]):
this is no longer part of the implementation some changes were need to comply with the coverages.

2021-03-19 17:28 UTC, jGonzalez-CCPO reviewed
this no longer apply

2021-03-19 18:36 UTC, jGonzalez-CCPO commented
List vs enum: 


<img width="601" alt="Screen Shot 2021-03-19 at 14 36 32" src="https://user-images.githubusercontent.com/77741090/111827645-83b97580-88c0-11eb-8642-4624dd71dafb.png">

2021-03-19 18:37 UTC, jGonzalez-CCPO commented
as you see the list performed better and allows for cover the criteria of a default "production" environment.

2021-03-19 18:40 UTC, jGonzalez-CCPO commented
![Uploading Screen Shot 2021-03-19 at 14.40.14.png…]()

2021-03-22 18:09 UTC, jeffsegal-ccpo approved these changes
Looks good to me, thanks Jesus.

2021-03-22 18:59 UTC, kylelaker-ccpo approved these changes
The next time we get a chance to touch some of this code, we should see whether it'd be possible to avoid some of this roundtripping to/from `.value` with `configparser`. Looks good though. Thanks for the work, Jesus!

2021-03-22 19:54 UTC, jasonburkert-ccpo approved these changes

2021-03-22 21:06 UTC, jasonburkert-ccpo commented
@jGonzalez-CCPO Please rebase with 'develop'.  I attempted but there is a conflict to be resolved.

2021-03-22 21:33 UTC, merged