AT-6129 Added new config to determine whether or not to validate cert
dod-ccpo/atat pull request #2237
Opened 2021-04-06 14:58 UTC by anhtran-ccpo

2021-04-07 14:09 UTC, jasonburkert-ccpo commented
Will review.

2021-04-07 20:05 UTC, jeffsegal-ccpo requested changes

2021-04-07 20:21 UTC, anhtran-ccpo commented on atat/app.py
> +        "SAML_SSL_VERIFY": config.getboolean("default", "SAML_SSL_VERIFY"),
Didn't i already add this to `base.ini`? This converts it from a string to a boolean for the config when its being used

2021-04-07 21:57 UTC, jasonburkert-ccpo commented on README.md
> +  `SAML_SSL_VERIFY`: Boolean that says whether to fetch the IDP metadata to validate the cert or not.
Other SAML related config vars mention a default behavior.  Do we need the same here?

2021-04-07 22:13 UTC, anhtran-ccpo commented on README.md
> +  `SAML_SSL_VERIFY`: Boolean that says whether to fetch the IDP metadata to validate the cert or not.
I guess because the ticket says to default to True for most cases so I am not sure what to put down when it needs to be false.

2021-04-08 14:08 UTC, jeffsegal-ccpo commented on README.md
> +  `SAML_SSL_VERIFY`: Boolean that says whether to fetch the IDP metadata to validate the cert or not.
Only needs to be false if we're troubleshooting

2021-04-08 14:08 UTC, jeffsegal-ccpo commented on atat/app.py
> +        "SAML_SSL_VERIFY": config.getboolean("default", "SAML_SSL_VERIFY"),
Sorry that's my bad, I see it.

2021-04-08 14:08 UTC, jeffsegal-ccpo approved these changes

2021-04-08 14:26 UTC, jasonburkert-ccpo commented on atat/app.py
> +    Loops all the configuration settings in a given section of a
I appreciate that you catch and fix misspellings.

2021-04-08 14:28 UTC, jasonburkert-ccpo commented on atat/routes/saml_helpers.py
> +        # more distinguishing detail than that
Tricky one.

2021-04-08 14:36 UTC, jeffsegal-ccpo commented on atat/routes/saml_helpers.py
> +        # more distinguishing detail than that
There was a running joke in @anhtran-ccpo and my old project wherein the code base we inherited there years ago contained some amazing spelling errors, including a column named `dinguished_user` rather than `distinguished_user`, so this typo was extremely enjoyable to see.

2021-04-08 14:40 UTC, anhtran-ccpo commented on atat/app.py
> +    Loops all the configuration settings in a given section of a
pycharm points a lot of these out so i take opportunities to go in and fix them if i can

2021-04-08 14:41 UTC, anhtran-ccpo commented on atat/routes/saml_helpers.py
> +        # more distinguishing detail than that
Jeff and I had a similar misspelling on our previous project so it was kind of funny this was misspelled here too

2021-04-08 15:53 UTC, jasonburkert-ccpo commented on atat/routes/saml_helpers.py
> +        # more distinguishing detail than that
lol @ dingquished

2021-04-08 16:10 UTC, jasonburkert-ccpo approved these changes
Ran unit tests locally. Looks good.
![image](https://user-images.githubusercontent.com/77642966/114060464-66464e80-9863-11eb-96ef-3823f9e1347d.png)

2021-04-08 16:10 UTC, merged