AT-6113 Develop initial test cases that leverage page object framework
dod-ccpo/atat pull request #2240
Opened 2021-04-07 14:39 UTC by jGonzalez-CCPO

Building on the work completed in AT-6112: Create the framework necessary to call specific objects in the HTML FUNCTIONAL TESTING , we will be creating test cases for the following pages:
Login Scenario
Create Portfolio

Login scenario executes successfully and can report success/failure

Create Portfolio executes successfully and can report success/failure

https://ccpo.atlassian.net/browse/AT-6113

2021-04-07 14:40 UTC, jGonzalez-CCPO commented
Pending changes

2021-04-07 14:53 UTC, jGonzalez-CCPO commented
pending changes

2021-04-07 21:42 UTC, jasonburkert-ccpo commented on pyproject.toml
> +selenium = "^3.141.0"
This should probably be under `dev-dependencies`.   I would expect there should be a corresponding targeted change to file `poetry.lock` with this new dependency.

2021-04-07 21:43 UTC, jasonburkert-ccpo commented on .gitignore
> +dump.rdb
Can we add a comment about the file being ignored?

2021-04-07 22:17 UTC, jGonzalez-CCPO commented on pyproject.toml
> +selenium = "^3.141.0"
it was there already in fack it was 2 times

2021-04-07 22:18 UTC, jGonzalez-CCPO commented on pyproject.toml
> +selenium = "^3.141.0"
selenium = "^3.141.0" 
selenium = "*"

2021-04-08 13:24 UTC, jasonburkert-ccpo commented on uitests/TestFramework/Driver_Notes/LICENSE:Zone.Identifier
> +ReferrerUrl=C:\Users\EdwardHoward(ASG)\Downloads\edgedriver_win64 (3).zip
Do we need this ReferrerUrl in here?  Probably shouldn't have this user-specific path in the repo.

2021-04-08 13:25 UTC, jasonburkert-ccpo commented on uitests/TestFramework/Driver_Notes/LICENSE:Zone.Identifier
> +ReferrerUrl=C:\Users\EdwardHoward(ASG)\Downloads\edgedriver_win64 (3).zip
This applied to the other files ending in "Zone.Identifier" as well.

2021-04-08 13:28 UTC, jasonburkert-ccpo commented on uitests/TestFramework/pageObjects/CommonMethods.py
> +class Jedi_Common_Methods:
The fate of the DoD JEDI contract is uncertain.  We should avoid using this term.

2021-04-08 13:31 UTC, kylelaker-ccpo commented on uitests/TestFramework/Driver_Notes/LICENSE:Zone.Identifier
> +ReferrerUrl=C:\Users\EdwardHoward(ASG)\Downloads\edgedriver_win64 (3).zip
A `Zone.Identifier` should never be committed. These are artifacts of copying from Windows host to WSL. They can all be removed (both here and locally).

2021-04-08 13:38 UTC, jasonburkert-ccpo commented on uitests/TestFramework/testCases/conftest.py
> +    }]
There's far too much duplication of the same code here.  Most of the content of these python dicts is repetitive.  Please follow the DRY principal.  There's 60+ lines here, aim for less than half that.

2021-04-08 13:39 UTC, jasonburkert-ccpo commented on uitests/TestFramework/testCases/conftest.py
> +    #     print("Launching Firefox Browser.....")
Let's remove this.

2021-04-08 13:45 UTC, jasonburkert-ccpo commented on uitests/TestFramework/testCases/test_create_app.py
> +    url2 = ReadConfig.getLoginLocalURL()
Why _url2_?  Is there a _url1_?  Perhaps __url_ to indicate it is only used internally?  Reference: https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles

2021-04-08 13:50 UTC, jasonburkert-ccpo commented on uitests/TestFramework/utilities/readProperties.py
> +        return url
Refactor to simply `return os.getenv("baseURL")`.

Apply same to other _get_ methods.

2021-04-08 13:59 UTC, jGonzalez-CCPO commented on uitests/TestFramework/Driver_Notes/LICENSE:Zone.Identifier
> +ReferrerUrl=C:\Users\EdwardHoward(ASG)\Downloads\edgedriver_win64 (3).zip
uitests/TestFramework/Driver_Notes/LICENSE:Zone.Identifier 

this was take care in a latter commit

2021-04-08 14:08 UTC, kylelaker-ccpo commented
`static/img/test.pdf` should not be at that location. Files under that path are always accessible on a deployed application. For example, this would be available under `https://<namespace.atat.dev/static/img/test.pdf` just as `static/img/minus.svg` is available at `https://<namespace>.atat.dev/static/img/minus.svg`.

Files to support tests should be stored in the `tests/` or `uitests/` directory as appropriate.

2021-04-13 18:56 UTC, jasonburkert-ccpo requested changes
Browser versions in conftest.py should be set to latest so they update dynamically, or at a minimum change Edge to 89 so it's in sync with Chrome.

File `static/img/test.pdf` should be moved to `uitests/resources` or `tests/resources`.  The file should not be available in a hypothetical deployment at https://production.atat.dev/static/img/test.pdf

The parameter -n=2 should be removed from the pytest commands.  Myself and two other people have been unsuccessful attempting to include that parameter.

2021-04-13 18:56 UTC, jasonburkert-ccpo commented on uitests/framework/README.md
> + (.venv) $ pytest -n=2 -s -v -m smoke uitests/* --browser chrome
I encountered errors when including parameter `-n=2.`  This was removed from the Confluence instructions for now.  This should probably be removed from the README as well or replaced with a working command for parallel test execution.

2021-04-13 18:56 UTC, jasonburkert-ccpo commented on uitests/framework/test_cases/conftest.py
> +}
I suggest changing the `browser_version` to **latest** if possible.
If not possible, the Edge version should be changed to **89.0**.

2021-04-13 19:37 UTC, ehoward-ccpo commented on uitests/framework/README.md
> + (.venv) $ pytest -n=2 -s -v -m smoke uitests/* --browser chrome
Removed this section for now and will revisit at a later point.

2021-04-13 19:37 UTC, ehoward-ccpo commented on uitests/framework/test_cases/conftest.py
> +}
Updated the browser version to "latest" for all supported browsers

2021-04-13 21:20 UTC, jasonburkert-ccpo approved these changes
Peer reviewed.  All requested changes have been addressed.

2021-04-14 03:22 UTC, jasonburkert-ccpo commented
Rebasing involved several merge conflicts to resolve.
`git pull --rebase origin develop && git push --force`

2021-04-14 04:05 UTC, merged