changed EIFSAttributes in saml_helper to GlobalDirectoryAttributes
dod-ccpo/atat pull request #2266
Opened 2021-04-21 19:26 UTC by DGabriel-CCPO

Title says it all

2021-04-23 18:01 UTC, jeffsegal-ccpo requested changes

2021-04-23 18:40 UTC, DGabriel-CCPO commented on atat/routes/saml_helpers.py
> +class GlobalDirectoryAttributes:
Has been changed in the code.

2021-04-23 20:47 UTC, jeffsegal-ccpo commented on atat/routes/saml_helpers.py
> +class GlobalDirectoryAttributes:
Don't see it yet - did you forget to do a push?

2021-04-23 20:49 UTC, DGabriel-CCPO commented on atat/routes/saml_helpers.py
> +class GlobalDirectoryAttributes:
<img width="805" alt="Screen Shot 2021-04-23 at 2 48 51 PM" src="https://user-images.githubusercontent.com/79282243/115928278-15c61800-a443-11eb-9deb-76aaaa8adb6d.png">
I don't know why it didn't update the pull request

2021-04-23 20:59 UTC, jeffsegal-ccpo commented on atat/routes/saml_helpers.py
> +class GlobalDirectoryAttributes:
M ay be because it's behind `develop` itself? 

![image](https://user-images.githubusercontent.com/75797900/115929144-44e58500-a455-11eb-908b-a5852546e196.png)

2021-04-25 02:27 UTC, jasonburkert-ccpo commented
@jeffsegal-ccpo Do you approve of the requested changes?

2021-04-26 17:12 UTC, jeffsegal-ccpo approved these changes

2021-04-26 17:12 UTC, merged