Feature/at 6116 create scripts that backfill portfolios task orders
dod-ccpo/atat pull request #2296
Opened 2021-04-29 20:46 UTC by jGonzalez-CCPO

2021-05-14 14:14 UTC, jasonburkert-ccpo commented on script/data-feeder/add-clin-example.json
> +            "obligated_amount": "1002"
Are the mixed separators intentional?

2021-06-05 18:18 UTC, jGonzalez-CCPO commented
GitHub is reporting that it fail UI test but in browser stack show that it pass all test: 

https://automate.browserstack.com/dashboard/v2/builds/ba198cf8e0ea60d71d0d7ea0ab896b8f7e507dde/sessions/e5030264457eee549d802abcd8d883ef3e6a24c2

2021-06-09 22:12 UTC, kylelaker-ccpo requested changes

2021-06-09 22:12 UTC, kylelaker-ccpo commented on script/data_feeder.py
> +    # TODO: return list of portfolios by dod_id of a manager user.
Resolve or remove TODO

2021-06-09 22:12 UTC, kylelaker-ccpo commented on script/data_feeder.py
> +    cli_app()
Everything defined in here `<name> = ` is technically a global variable. That is why `web_app` for example is available everywhere. These should all be in UPPER_SNAKE_CASE.

2021-06-16 00:10 UTC, jGonzalez-CCPO commented on script/data_feeder.py
> +    """
This was change as christ and tom requested please check the newest version.

2021-06-16 00:21 UTC, jGonzalez-CCPO commented on script/data_feeder.py
> +    LIST_SERVICE_BRANCHES.append(branch[0])
👍

2021-06-16 00:24 UTC, jGonzalez-CCPO commented on script/data_feeder.py
> +def get_atat_users_list(filter_by: str = None) -> List[User]:
👍 I already importing Optional. good catch.

2021-06-16 00:45 UTC, jGonzalez-CCPO commented on script/data_feeder.py
> +    if filter_by in ["all", "ccpo", "has_project"]:
When I design this method I wanted to look for users from the CCPO and also the ones that are a manager (has_projects) but there wasn't any lookup for it. and I didn't want to do any invasive code on the ATAT. So I left it as a reference. 

What do you recommend to do add a todo for that or just deleted the has_project option?

2021-06-16 00:48 UTC, jGonzalez-CCPO commented on script/data_feeder.py
> +    if task_order_id and clins and len(clins) > 0:
Sorry, In JS is good practice to verify if the variable exists before verifying if it has a value. So, it does not crash the execution.

2021-06-16 00:48 UTC, jGonzalez-CCPO commented on script/data_feeder.py
> +    if task_order_id and clins and len(clins) > 0:
i will change to what you recommend.

2021-06-16 00:57 UTC, jGonzalez-CCPO commented on script/data_feeder.py
> +def get_value_if_present(request: dict = None, key: str = None) -> any:
👍

2021-06-16 00:58 UTC, jGonzalez-CCPO commented on script/data_feeder.py
> +        is_good(False)
What...!! that is cool.

2021-06-16 01:03 UTC, jGonzalez-CCPO commented on script/data_feeder.py
> +            print("portfolios_request", portfolios_request)
I guess not but still required portfolios_request down the road. can I declare that variable out of the scope of with: and then close it after accessing the file?

2021-06-16 14:18 UTC, kylelaker-ccpo commented on script/data_feeder.py
> +    if filter_by in ["all", "ccpo", "has_project"]:
Delete it please. If there is a later ticket that will add that functionality, then that's great. But let's not leave unclear and unimplemented values in the script.

2021-06-16 14:20 UTC, kylelaker-ccpo commented on script/data_feeder.py
> +            print("portfolios_request", portfolios_request)
`portfolios_request` will continue to exist after the file has been closed. the `dict` there does not hold a reference to the underlying file.

2021-06-16 23:13 UTC, jGonzalez-CCPO commented on script/data_feeder.py
> +            "authorized me to upload the task order.?"
may be a make mistake but I was sure I copy and paste this from the app dialogs. let me check this out. good catch.

2021-06-16 23:19 UTC, jGonzalez-CCPO commented on script/data_feeder.py
> +            "authorized me to upload the task order.?"
fixed

2021-06-16 23:21 UTC, jGonzalez-CCPO commented on script/data_feeder.py
> +def sing_atat_task_order(task_order: TaskOrder = None, signer_dod_id: str = None):
thanks

2021-06-17 00:14 UTC, jGonzalez-CCPO commented on script/data_feeder.py
> +def is_valid_clin_type(clin_type: str = "") -> bool:
again my JS mind thinking of default to fail-save. Sorry.

2021-06-17 21:54 UTC, jGonzalez-CCPO commented on script/data_feeder.py
> +    return True if re.match(r"^\d{4}$", clin_number) else False
I think the method re.match does not have an explicit bool return. I can be wrong.

2021-06-21 19:12 UTC, kylelaker-ccpo requested changes

2021-06-21 19:12 UTC, kylelaker-ccpo commented on pyproject.toml
> +python = "~3.9"
Has nothing to do with Python 4. The error message:

```
  SolverProblemError

  The current project's Python requirement (>=3.9.0,<4.0.0) is not compatible with some of the required packages Python requirement:
    - questionary requires Python >=3.6,<3.10, so it will not be satisfied for Python >=3.10,<4.0.0

  Because questionary (1.9.0) requires Python >=3.6,<3.10
   and no versions of questionary match >1.9.0,<2.0.0, questionary is forbidden.
  So, because atat depends on questionary (^1.9.0), version solving failed.
```

The issue is that `questionary`, one of the new dependencies added in this PR, specifies a very restrictive Python version compatibility, explicitly declaring itself incompatible with Python 3.10. This will make it more difficult to adopt newer versions of Python in the future.

I was already hesitant about pulling in three new dependencies to support this effort, especially since `click` (which we're already pulling in) provides a good-enough experience for the vast majority of Python CLIs. Can you please provide justification for why bringing this dependency can be justified by the higher maintenance burden we will face?

2021-06-21 19:12 UTC, kylelaker-ccpo commented on script/data_feeder.py
> +    if len(clins) < 1:
Why was this marked as resolved if it wasn't done?

2021-06-21 19:12 UTC, kylelaker-ccpo commented on script/data_feeder.py
> +    return True if re.match(r"^\d{4}$", clin_number) else False
While it does not have an explicit bool match, as far as I can tell, there isn't a need to specifically have an actual boolean. Having something with a well-defined `bool()` method is good enough. And that's what `re.match` will do. It will return something falsey if there are not any matches.

2021-06-21 19:12 UTC, kylelaker-ccpo commented on script/data_feeder.py
> +    return True if re.match(r"^\d{4}$", clin_number) else False
Please make this change everywhere else as well. Or explain why it cannot be done.

2021-06-21 19:21 UTC, jGonzalez-CCPO commented on package.json
> +    "uuid": "^8.3.2",
it was not declared on the package.json. and ask for it. 
I guess it was in the yarn.lock but no declare on the package.json. 

without it was not compiling the yarn watch.

2021-06-21 19:32 UTC, jGonzalez-CCPO commented on script/data_feeder.py
> +    return True if re.match(r"^\d{4}$", clin_number) else False
I did that change everywhere. but it is reported as smells check the report of sonar cloud

2021-06-22 15:45 UTC, jGonzalez-CCPO commented on format
> +Script started on Wed Jun 16 20:08:28 2021
deleted

2021-06-22 15:46 UTC, jGonzalez-CCPO commented on package.json
> +    "uuid": "^8.3.2",
@kylelaker-ccpo does this resolve this?

2021-06-22 15:47 UTC, jGonzalez-CCPO commented on script/data_feeder.py
> +    return True if re.match(r"^\d{4}$", clin_number) else False
Are you ok ignoring the smells?

2021-06-22 15:56 UTC, jGonzalez-CCPO commented on pyproject.toml
> +python = "~3.9"
My thought process on this is that an update can be delivered on Questionary any time before 3.10 is adopted. 

Also, Questionary is doing a lot of the weight work on the UI Cli that otherwise, a would have to write a lot of code for. I will prefer it if we get in compliance with today's requirements. 

What do you see as our way forward?

2021-06-23 18:44 UTC, kylelaker-ccpo commented on pyproject.toml
> +python = "~3.9"
I'd like to see this documented somewhere, potentially Confluence, that we are accepting this trade off.

2021-06-23 18:46 UTC, kylelaker-ccpo commented on script/data_feeder.py
> +    return True if re.match(r"^\d{4}$", clin_number) else False
I'd like to the type hints updated. `re.Match` (capital `M` is intentional) instead of `bool`

2021-06-23 18:49 UTC, kylelaker-ccpo commented on package.json
> +    "uuid": "^8.3.2",
I still don't understand why it is included in this PR. Or really, why any changes are being made to `package.json` at all.

2021-06-23 19:20 UTC, kylelaker-ccpo commented on pyproject.toml
> +python = "~3.9"
Thanks for documenting.

2021-06-24 02:24 UTC, jGonzalez-CCPO commented on script/data_feeder.py
> +    return True if re.match(r"^\d{4}$", clin_number) else False
done.

2021-06-24 02:25 UTC, jGonzalez-CCPO commented on script/data_feeder.py
> +    return True if re.match(r"^\d{4}$", clin_number) else False
✅

2021-06-24 02:37 UTC, jGonzalez-CCPO commented on package.json
> +    "uuid": "^8.3.2",
"one of the greatest mysteries in life", the only thing needed for something to get broken is that it was fine moments before. I can only see how to get better in the future. 
 
I just found the bug and I fix the bug so it can compile well. 

Do you want to make a recommendation to stop relying on the locks files since we are up today on all packages there should not be any need for the use of it? And that would make it easier in the future to catch this type of issues? 

Or what do you think is the best way to go forward with this?

2021-06-24 02:40 UTC, jGonzalez-CCPO commented
All issues and comments answered and changes push. waiting for updates.

2021-06-24 13:27 UTC, kylelaker-ccpo approved these changes
My comments have largely been addressed. Still confused about the `package.json` stuff but honestly, we can just open a new PR to undo that if it causes issues. Thanks for your work on this, Jesus.

2021-06-24 13:27 UTC, merged

2021-06-24 13:44 UTC, jGonzalez-CCPO commented
thanks for your hard work too @kylelaker-ccpo