Feature/at 6183
dod-ccpo/atat pull request #2375
Opened 2021-05-18 23:31 UTC by DGabriel-CCPO

Application ellipse was not accessible to keyboard-only users.  implemented the required fix to make accessible

2021-05-19 15:30 UTC, kylelaker-ccpo commented
A recent update to `prettier` applies different JS formatting to this segment of code. Locally, please run `script/update` followed by `script/format` to resolve the formatting issue.

2021-05-27 16:56 UTC, jGonzalez-CCPO requested changes

2021-05-27 16:56 UTC, jGonzalez-CCPO commented on templates/components/toggle_menu.html
> +  <div aria-haspopup="true"
chang this to a button tag.

2021-05-27 19:30 UTC, jGonzalez-CCPO commented
Please fix the styling issue: the background on the element containing the button gets changed when hovering over the element.

2021-05-27 19:38 UTC, jGonzalez-CCPO requested changes

2021-05-27 19:38 UTC, jGonzalez-CCPO commented on styles/components/_toggle_menu.scss
> +    background-color: $color-aqua-lightest;
This might be the right cascade for the hover background.  

```
toggle-menu
   button:hover
     .accordion-table__item__toggler{
          STYLE 
      }
```

2021-05-27 19:52 UTC, jGonzalez-CCPO reviewed
hover issue was resolve when using tabs and enter and click

2021-05-27 19:52 UTC, jGonzalez-CCPO commented on styles/components/_toggle_menu.scss
> +    background-color: $color-aqua-lightest;
Expample:

```
&:hover,
  &--active {
   background-color: white;
    .accordion-table__item__toggler{
        background-color: $color-aqua-lightest;
    }

  }
```

2021-05-27 19:54 UTC, jGonzalez-CCPO requested changes

2021-05-27 19:54 UTC, jGonzalez-CCPO commented on styles/components/_toggle_menu.scss
> +  &:hover,
&:active,

2021-05-27 20:07 UTC, jGonzalez-CCPO approved these changes

2021-06-02 13:19 UTC, merged