AT-5882 View a user’s portfolio permissions
dod-ccpo/atat pull request #2378
Opened 2021-05-20 02:42 UTC by jGonzalez-CCPO

Description
As a CCPO admin, I want to see all the portfolios a user is part of, so that I can quickly find any portfolios that the user asks for my help with.
Out of scope for this ticket: the … button that leads to editing permissions. That is covered in AT-5883: Drop down menu to edit portfolio permissionsTO DO 
See below for an image of the component and see the User Detail View v2 page in Abstract for design specs. 
Note: Abstract/Invision links will only be available until June 2021. A PNG version of the view from the above Abstract link is retained for reference on Confluence here: User Detail View v2.png. Please see Design Files and Assets  in Confluence for instructions on how you can view design specs using Sketch.

Acceptance Criteria
the table should include all portfolios for which the selected user has a role
the table should include:
portfolio name
user’s role in the portfolio
portfolio name should be sortable alphabetically
default sort is portfolio in alphabetical order
if the CCPO admin clicks the portfolio, they’re brought to the portfolio detail view

2021-05-20 04:16 UTC, jGonzalez-CCPO commented
Need to finish coverage

2021-05-20 17:15 UTC, jGonzalez-CCPO commented
Ready for PR

2021-05-20 18:10 UTC, kylelaker-ccpo requested changes

2021-05-20 18:10 UTC, kylelaker-ccpo commented on atat/routes/admin/admin.py
> +        mindate=pendulum.now(tz="UTC").subtract(days=365),
```suggestion
        mindate=pendulum.now(tz="UTC").subtract(years=1),
```

2021-05-20 18:10 UTC, kylelaker-ccpo commented on atat/routes/admin/admin.py
> +        portfolio_roles_sort = portfolio_roles_sort[::-1]
```suggestion
    reverse = order_asc == "-1"
    portfolio_roles_sort = sorted(
        portfolio_roles,
        key=lambda portfolio_role: portfolio_role.PortfolioRole.portfolio.name,
        reverse=reverse
    )
```

2021-05-20 18:10 UTC, kylelaker-ccpo commented on tests/models/test_portfolio_role.py
> +from _pytest._code import ExceptionInfo
Looks this was an unintentional import?

```suggestion
```

2021-05-20 18:10 UTC, kylelaker-ccpo commented on atat/domain/portfolio_roles.py
> +    def get_all_by_user(cls, user_id: str = None) -> [PortfolioRole]:
```suggestion
    def get_all_by_user(cls, user_id: Optional[str] = None) -> List[PortfolioRole]:
```

This is not a valid type annotation as-written. We should go over type hints at some point. The new code will require also importing `from typing import List, Optional` if that's not already imported.

2021-05-20 18:10 UTC, kylelaker-ccpo commented on tests/models/test_portfolio_role.py
> +    ), "PortfolioRole default description start with <PortfolioRole"
```suggestion
    assert (
        repr(port_role).startswith("<PortfolioRole") is True
    ), "PortfolioRole default description start with <PortfolioRole"
```

You can't guarantee that `__str__` calls `__repr__` and we don't want to require that behavior. We also should probably check that:

```
for perm_set in perm_sets:
  assert perm_set.name in repr(port_role)
```

or something like that.

2021-05-20 18:10 UTC, kylelaker-ccpo commented on tests/models/test_portfolio_role.py
> +    assert user_portfolio_role.is_owner is False, "user role should not be owner"
```suggestion
    assert owner_portfolio_role.is_owner, "owner role should be owner"
    assert not user_portfolio_role.is_owner, "user role should not be owner"
```

2021-05-20 18:10 UTC, kylelaker-ccpo commented on tests/models/test_portfolio_role.py
> +    assert user_portfolio_role.is_manager is False, "user role should not be manager"
```suggestion
    assert owner_portfolio_role.is_manager, "owner role should be manager"
    assert not user_portfolio_role.is_manager, "user role should not be manager"
```

2021-05-20 18:35 UTC, jasonburkert-ccpo requested changes
Please rename file `templates/admin/fragments/user_portafolios_roles.html` to `templates/admin/fragments/user_portfolios_roles.html`

2021-05-20 18:36 UTC, jasonburkert-ccpo commented
> Please rename file `templates/admin/fragments/user_portafolios_roles.html` to `templates/admin/fragments/user_portfolios_roles.html`

Agree if not used, just remove.

2021-05-20 18:38 UTC, jGonzalez-CCPO commented
@jasonburkert-ccpo https://github.com/dod-ccpo/atat/pull/2378/commits/fc0e8efea60ea3c8a0adde8d974bc7077daefd29

2021-05-20 18:40 UTC, jasonburkert-ccpo commented
Yep, see the updates now.  Thanks.

2021-05-20 18:41 UTC, jGonzalez-CCPO commented
wait i adding libraries

2021-05-20 18:45 UTC, jasonburkert-ccpo commented
Yeah, seeing `script/update` failure.
```
jasonburkert@DESKTOP-FCCO10J:~/atat$ . /home/jasonburkert/atat/.venv/bin/activate
(.venv) jasonburkert@DESKTOP-FCCO10J:~/atat$ script/update
mkdir: cannot create directory ‘uploads’: File exists
Installing dependencies from lock file

No dependencies to install or update
yarn install v1.22.5
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.45s.
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Traceback (most recent call last):
  File "./script/seed_roles.py", line 10, in <module>
    from atat.app import make_app
  File "/home/jasonburkert/atat/atat/app.py", line 18, in <module>
    from atat.domain.portfolios import Portfolios
  File "/home/jasonburkert/atat/atat/domain/portfolios/__init__.py", line 1, in <module>
    from .portfolios import (
  File "/home/jasonburkert/atat/atat/domain/portfolios/portfolios.py", line 9, in <module>
    from atat.domain.invitations import PortfolioInvitations
  File "/home/jasonburkert/atat/atat/domain/invitations.py", line 6, in <module>
    from atat.domain.portfolio_roles import PortfolioRoles
  File "/home/jasonburkert/atat/atat/domain/portfolio_roles.py", line 12, in <module>
    class PortfolioRoles(object):
  File "/home/jasonburkert/atat/atat/domain/portfolio_roles.py", line 28, in PortfolioRoles
    def get_all_by_user(cls, user_id: Optional[str] = None) -> List[PortfolioRole]:
NameError: name 'Optional' is not defined
```

2021-05-20 18:46 UTC, jGonzalez-CCPO commented on tests/models/test_portfolio_role.py
> +from _pytest._code import ExceptionInfo
I was testing a way to make an assertion of an exiting exception. it never works. approved your change here.

2021-05-20 18:47 UTC, jGonzalez-CCPO commented on atat/routes/admin/admin.py
> +        portfolio_roles_sort = portfolio_roles_sort[::-1]
super smart, I didn't think about this. more clear.

2021-05-20 18:47 UTC, jGonzalez-CCPO commented on atat/routes/admin/admin.py
> +        mindate=pendulum.now(tz="UTC").subtract(days=365),
make sance

2021-05-20 18:47 UTC, jGonzalez-CCPO commented on atat/models/portfolio_role.py
> +        return "edit_portfolio_admin" in permission_sets_list
nice to know about has_permission_set

2021-05-20 18:48 UTC, jGonzalez-CCPO commented on tests/models/test_portfolio_role.py
> +    ), "a valid user id should return a list of the roles of the user."
Spanglish Typo :( - thank for catching that.

2021-05-20 18:48 UTC, jGonzalez-CCPO commented on templates/admin/fragments/user_portafolios_roles.html
> +<!DOCTYPE html>
not need for this for now.

2021-05-20 18:49 UTC, jGonzalez-CCPO commented on atat/domain/portfolio_roles.py
> +    def get_all_by_user(cls, user_id: str = None) -> [PortfolioRole]:
Doing the librarires now.

2021-05-20 18:51 UTC, jGonzalez-CCPO commented
testing changes now on local

2021-05-20 19:01 UTC, jGonzalez-CCPO commented on tests/models/test_portfolio_role.py
> +    ), "PortfolioRole default description start with <PortfolioRole"
jum, good to know.

2021-05-20 19:02 UTC, jGonzalez-CCPO commented on tests/models/test_portfolio_role.py
> +    assert user_portfolio_role.is_manager is False, "user role should not be manager"
ok

2021-05-20 19:03 UTC, jGonzalez-CCPO commented
@jasonburkert-ccpo now is tested and ready for PR

2021-05-20 19:27 UTC, jasonburkert-ccpo commented on tests/models/test_portfolio_role.py
> +    ), "PortfolioRole default description start with <PortfolioRole"
@kylelaker-ccpo Had to look this up.  I didn't know there were two ways to get a string representation.

2021-05-20 19:35 UTC, jasonburkert-ccpo commented on tests/models/test_portfolio_role.py
> +    ), "PortfolioRole default description start with <PortfolioRole"
Oh I see, PortfolioRole class implements __repr__ directly and includes the tested string.

2021-05-20 20:09 UTC, jGonzalez-CCPO commented
need to fixed a style

2021-05-21 15:34 UTC, jasonburkert-ccpo approved these changes

2021-05-21 15:41 UTC, jasonburkert-ccpo approved these changes
I think this is ready to merge.
![image](https://user-images.githubusercontent.com/77642966/119163565-84d66280-ba29-11eb-9349-aa55f9d41f9d.png)

2021-05-21 16:51 UTC, kylelaker-ccpo approved these changes

2021-05-21 16:51 UTC, merged