Feature/AT-5959 Remove non-actionable TODOs
dod-ccpo/atat pull request #2387
Opened 2021-05-24 20:54 UTC by zachclark-ccpo

Code base contained 40+ instances of the TODO markers, and these TODOs were decided to be non-actionable, deleting them to prevent further confusion.

Confluence Page discussing Non-actionable TODOs: https://ccpo.atlassian.net/wiki/spaces/AT/pages/edit-v2/1299087643
Ticket: https://ccpo.atlassian.net/browse/AT-5959

2021-05-24 21:28 UTC, kylelaker-ccpo requested changes
Let's talk about removing a31aaa0 from this PR. Since the only usage is in the function that tests it, we probably can remove both the function and it's test. Therefore, we can either remove both in this PR or create a ticket to do so.

And since we'll be modifying history anyway, let's talk about doing a rebase to squash 2c60325 into b0cbe48.

The former is a blocker to approval; the latter is a nice-to-have.

2021-05-24 22:09 UTC, jasonburkert-ccpo approved these changes
These removals look reasonable.

2021-05-24 22:15 UTC, jasonburkert-ccpo commented
Re: https://github.com/dod-ccpo/atat/commit/a31aaa040a5c2da0511f16cd3ca0b0e41e9a3c96  Agree.  Please remove.

https://github.com/dod-ccpo/atat/search?q=log_system_event

![image](https://user-images.githubusercontent.com/77642966/119413586-ee6d9f80-bcbb-11eb-8153-8f27d8946638.png)

2021-05-25 16:01 UTC, zachclark-ccpo commented
> Re: [a31aaa0](https://github.com/dod-ccpo/atat/commit/a31aaa040a5c2da0511f16cd3ca0b0e41e9a3c96) Agree. Please remove function `log_system_event`
> 
> https://github.com/dod-ccpo/atat/search?q=log_system_event
> 
> ![image](https://user-images.githubusercontent.com/77642966/119413586-ee6d9f80-bcbb-11eb-8153-8f27d8946638.png)

Hey Jason, for removing log_system_event , wont it mess up this pagination function? 
Should I remove it and leave it as:
```
@pytest.mark.audit_log
def test_paginate_audit_log():
    events = AuditLog.get_all_events(pagination_opts={"per_page": 25, "page": 2})
    assert len(events) == 25
```
Or is it better to remove the pagination test entirely? Please advise.

2021-05-25 18:28 UTC, kylelaker-ccpo commented on tests/domain/test_audit_log.py
>      assert len(events) == 25
This test doesn't get run in the pipeline but would fail as-is. We're not logging any events so there's no way that there can be 25 of them :)

2021-05-25 18:28 UTC, kylelaker-ccpo commented on tests/domain/test_audit_log.py
>      )
Same concerns as other comment.

2021-05-25 21:12 UTC, kylelaker-ccpo commented
@zachclark-ccpo and @jasonburkert-ccpo looking at this further, I think we need to discuss the value of the `AuditLog` class. We always set `USE_AUDIT_LOG` to `false`; therefore it doesn't get tested (or used in deployed environments). If we remove these tests, we will lose code coverage for the `get_` functions on the `AuditLog` class which I don't want to do. But reworking them to hackily call action that will trigger audit events is suboptimal as well.

@zachclark-ccpo can you provide information on when this class and the related functions/methods were added (including PRs and potentially tickets) and perhaps we can have a discussion to evaluate the proper path forward on this?

I don't want to suggest removing tests for code that does get run; I don't want to keep dead code around; and I don't want to add too much complexity to what is largely a removal ticket. We may need to create a separate ticket to handle the deletion/updating of the `AuditLog` class but even that should have a conversation around desired outcomes. Sorry for asking different things on this and thank you for raising good questions about the removal.

2021-05-26 19:18 UTC, zachclark-ccpo commented
> @zachclark-ccpo and @jasonburkert-ccpo looking at this further, I think we need to discuss the value of the `AuditLog` class. We always set `USE_AUDIT_LOG` to `false`; therefore it doesn't get tested (or used in deployed environments). If we remove these tests, we will lose code coverage for the `get_` functions on the `AuditLog` class which I don't want to do. But reworking them to hackily call action that will trigger audit events is suboptimal as well.
> 
> @zachclark-ccpo can you provide information on when this class and the related functions/methods were added (including PRs and potentially tickets) and perhaps we can have a discussion to evaluate the proper path forward on this?
> 
> I don't want to suggest removing tests for code that does get run; I don't want to keep dead code around; and I don't want to add too much complexity to what is largely a removal ticket. We may need to create a separate ticket to handle the deletion/updating of the `AuditLog` class but even that should have a conversation around desired outcomes. Sorry for asking different things on this and thank you for raising good questions about the removal.

AuditLog base.ini toggle PR: https://github.com/dod-ccpo/atat/pull/1127

2021-05-26 20:45 UTC, kylelaker-ccpo approved these changes
Thanks for your work and attention to detail here. I really appreciate it. This is great for cleaning up a good chunk of the code base.

2021-05-26 20:46 UTC, merged