Feature/at 6229 update node
dod-ccpo/atat pull request #2410
Opened 2021-06-01 19:06 UTC by jGonzalez-CCPO

Description
Node.js 10, the current version in use on ATAT is end-of-life upstream (though still updated through the RHEL repos). This means that various libraries that we depend on are going to start dropping support for Node.js 10. In fact, node-sass has already done this in v6.0.0. See Bump node-sass from 5.0.0 to 6.0.0 by dependabot · Pull Request #2373 · dod-ccpo/atat for the pull request.

Other version of Node.js are available in the AppStream repositories from RHEL. See Releases | Node.js  for the Node.js release cycle.

Acceptance Criteria
1) Determine the new version of Node.js to use
2) Ensure that all dependencies are compatible with the new version or are update appropriately
3) Update the Dockerfiles to install the correct repository and package

4) Include documentation on how to upgrade local nodejs version on WSL & MacOS

5) Deploy application successfully

https://ccpo.atlassian.net/browse/AT-6229

2021-06-01 19:54 UTC, kylelaker-ccpo requested changes
Please update `README.md` to clarify the version of node. Please update `docs/WindowsSubsystemLinux.md` with information on installing `nvm` and using it to install Node.js v14.

2021-06-08 15:48 UTC, jasonburkert-ccpo commented on README.md
>    This is a requirement of [node-sass](https://github.com/sass/node-sass).  For macOS, use brew to install:
@jGonzalez-CCPO Kyle suggested removing this node-sass reference.
```suggestion
  For macOS, use brew to install:
```

2021-06-08 15:57 UTC, jasonburkert-ccpo commented on package.json
> +    "yarn": "^1.22.10",
Is this necessary?  It wasn't here previously.  But certainly WSL install instructions include `sudo apt install yarnpkg`, and README says atat requires yarn.

2021-06-08 18:13 UTC, jGonzalez-CCPO commented on README.md
>    This is a requirement of [node-sass](https://github.com/sass/node-sass).  For macOS, use brew to install:
done

2021-06-08 18:17 UTC, jGonzalez-CCPO commented on package.json
> +    "yarn": "^1.22.10",
I not pretty sure.

That regularly is used as a global dependency. 

But, I thought of saving the version used somewhere. 

This way even if you have the dependency on your global scope the app still runs since it has it locally in the project.

So, there you have the pros and the cons

2021-06-08 18:38 UTC, jasonburkert-ccpo commented on README.md
> +  ```
This is good.

2021-06-08 18:40 UTC, jasonburkert-ccpo commented on README.md
> +  read [nvm repo](https://github.com/nvm-sh/nvm/blob/master/README.md) for Troubleshooting.
This is all accurate, but I think @kylelaker-ccpo was suggesting use of nvm only for Windows and WSL.  So this would be in the Windows instructions but not here.  I think you should stick with the use of brew above for macOS.

2021-06-08 18:41 UTC, jasonburkert-ccpo commented on README.md
> +
I don't think you need any of this.

2021-06-08 18:42 UTC, jGonzalez-CCPO commented on README.md
> +  read [nvm repo](https://github.com/nvm-sh/nvm/blob/master/README.md) for Troubleshooting.
yes, the detail for Win are in:

https://github.com/dod-ccpo/atat/blob/1d7aaace66fcb63f61e54ef89ffedc139d7d9e41/docs/WindowsSubsystemLinux.md

as @kylelaker-ccpo requested.

2021-06-08 18:45 UTC, jGonzalez-CCPO commented on README.md
> +
There are people on the team that it will be their first time on NVM so I thought on make it very explicit how to work with it.

2021-06-08 18:46 UTC, jasonburkert-ccpo commented on docs/WindowsSubsystemLinux.md
> +$ curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
This is not using nvm to install nodejs.  This is using package `nodejs14` instead.  The addition of curl makes sense.

I would expect to see the following here.  This is from https://github.com/nvm-sh/nvm
`curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash`

2021-06-08 18:50 UTC, jGonzalez-CCPO commented on README.md
> +  read [nvm repo](https://github.com/nvm-sh/nvm/blob/master/README.md) for Troubleshooting.
The instruction of brew is for installing Node. 

The market instruction in this comment is for NVM.  
When you install nvm with brew it gets very buggy so is better to do it this way. 
also, the same instruction in this comment works in Unix, Mac and WSL.

I happen to include the extra steps you required for installing on Windows in the docs/WindowsSubsystemLinux.md file.

2021-06-08 18:54 UTC, jGonzalez-CCPO commented on docs/WindowsSubsystemLinux.md
> +$ curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
NVM is for switching node versions. while apt node14 is for installing node 14 as default on the WSL instance.

2021-06-08 18:55 UTC, jGonzalez-CCPO commented on docs/WindowsSubsystemLinux.md
> +$ curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
I will need to test on windows if this curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash also work but I guess it does, can you please try in yours?

2021-06-09 14:24 UTC, jasonburkert-ccpo commented on docs/WindowsSubsystemLinux.md
> +$ curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
Yes, I had good luck using nvm, installing it using that command (which is in the README at the git repo for the nvm project) and using it to install node 14 in this PR https://github.com/dod-ccpo/atat/pull/2397

2021-06-10 14:20 UTC, jGonzalez-CCPO commented
Please not merge until @kylelaker-ccpo  approved. 

Is waiting for another feature to be done before it can be merge.

2021-06-14 20:50 UTC, kylelaker-ccpo commented
cb0644e8e6cc1563ccbac846cf505e2c7a1a5e0f has been deployed to https://kal4.atat.dev.

2021-06-14 20:54 UTC, kylelaker-ccpo commented on package.json
> +    "yarn": "^1.22.10",
I would like to remove this as a dev dependency. We document the need to install this separately. And I'd rather not have everyone have two versions in different places.

2021-06-15 14:58 UTC, kylelaker-ccpo requested changes

2021-06-15 14:58 UTC, kylelaker-ccpo commented on yarn.lock
> +  integrity sha512-IanQGI9RRPAN87VGTF7zs2uxkSyQSrSPsju0COgbsKQOOXr5LtcVPeyXWgwVa0ywG3d8dg6kSYKGBuYK021qeA==
This needs to be removed to correspond with the removal from `package.json`

2021-06-15 15:33 UTC, jasonburkert-ccpo requested changes
I have a few suggested comments for the README.

2021-06-15 15:33 UTC, jasonburkert-ccpo commented on README.md
>    reload in development.
I've done a survey, and I recommend removing this.  I don't think anyone has used it in the last 6 months.  But I leave it up to you.

2021-06-15 15:33 UTC, jasonburkert-ccpo commented on docs/WindowsSubsystemLinux.md
> +done through other means.
I applaud this change.  Well caught.

2021-06-15 15:33 UTC, jasonburkert-ccpo commented on docs/WindowsSubsystemLinux.md
> +All of Redis, NodeJS v14 (LTS/fermium), Yarn, `xmlsec1`, and PostgreSQL are available through the
We don't mention version number for any of the other packages here.  Also, isn't it stylized as Node.js rather than NodeJS?
```suggestion
All of Redis, Node.js, Yarn, xmlsec1, and PostgreSQL are available through the
```

2021-06-15 15:33 UTC, jasonburkert-ccpo commented on docs/WindowsSubsystemLinux.md
> +$ sudo apt update
This is probably a good idea.

2021-06-15 15:33 UTC, jasonburkert-ccpo commented on docs/WindowsSubsystemLinux.md
> +$ sudo apt install curl redis nodejs postgresql yarnpkg xmlsec1
Agree with inclusion of `curl`, especially since using on the next line.  I think `nodejs` could be removed here.  The expected version of node is being installed below with `nvm install`.
```suggestion
$ sudo apt install curl redis postgresql yarnpkg xmlsec1
```

2021-06-15 15:33 UTC, jasonburkert-ccpo commented on package.json
> +  },
Could be make this more generic?
```suggestion
  "engines": {
    "node": ">=14.0.0 <15.0.0" 
  },
```

2021-06-15 15:33 UTC, jasonburkert-ccpo commented on yarn.lock
> +  integrity sha512-IanQGI9RRPAN87VGTF7zs2uxkSyQSrSPsju0COgbsKQOOXr5LtcVPeyXWgwVa0ywG3d8dg6kSYKGBuYK021qeA==
@kylelaker-ccpo Can you clarify?  Seems like you mean that yarn dependency should be removed in `package.json`, but I'm not sure I've understood you.

Could you have meant that the pending change (`engines` block) to `package.json` should be removed?

2021-06-15 15:33 UTC, jasonburkert-ccpo commented on README.md
> +  We recommend using Node Version Manager, or nvm, in order to update the version—and requirements—efficiently and simply.
```suggestion
  We recommend using Node Version Manager, or nvm, to manage your node installation. 
```

2021-06-15 15:33 UTC, jasonburkert-ccpo commented on README.md
> +  the script manually, or use the following cURL command:
```suggestion
  **Install:** To install, run the following command:
```

2021-06-15 16:16 UTC, jGonzalez-CCPO commented on yarn.lock
> +  integrity sha512-IanQGI9RRPAN87VGTF7zs2uxkSyQSrSPsju0COgbsKQOOXr5LtcVPeyXWgwVa0ywG3d8dg6kSYKGBuYK021qeA==
@jasonburkert-ccpo I forgot to script/update the yarn.lock that is fixed in my next commit. Good catch @kylelaker-ccpo

2021-06-15 16:20 UTC, jGonzalez-CCPO commented on package.json
> +  },
The version was tested for deployment and can not be changes.

2021-06-15 16:24 UTC, jGonzalez-CCPO commented on README.md
> +#### `python` >= 3.9
:)

2021-06-15 16:28 UTC, jGonzalez-CCPO commented on docs/WindowsSubsystemLinux.md
> +done through other means.
:)

2021-06-15 16:30 UTC, jGonzalez-CCPO commented on docs/WindowsSubsystemLinux.md
> +$ sudo apt update
👍

2021-06-15 16:46 UTC, jasonburkert-ccpo approved these changes

2021-06-15 16:53 UTC, merged

2021-06-15 16:55 UTC, jasonburkert-ccpo commented
@kylelaker-ccpo Gotcha.  I see now it had already been removed.