Updating naming convention to ATAT
dod-ccpo/atat pull request #2414
Opened 2021-06-02 17:16 UTC by danielgottlieb-ctr

updating naming to be purely ATAT

2021-06-03 13:58 UTC, kylelaker-ccpo commented
These modifications to the `alembic` scripts may actually break the migrations. I am not totally sure of that; we'll just need to pay special attention to that during the review. And we may actually need a _new_ migration that handles renaming JEDI->ATAT. Again, not sure; we just want to keep it in mind during testing and review (because the pipeline doesn't necessarily validate those),

2021-06-09 20:29 UTC, whit1206 requested changes
Please change all "ATAT Sevices" to "Cloud Services" amongst other changes. Thanks

2021-06-09 20:29 UTC, whit1206 commented on templates/emails/base.txt
> +ATAT is a DoD enterprise-wide solution for commercial cloud services.
change to "ATAT (Account Tracking and Automation Tool) is a web-based application that streamlines the cloud onboarding process for DoD and its Mission Partners"

2021-06-09 20:29 UTC, whit1206 commented on translations.yaml
> +  head: ATAT Services
change to "Cloud Services"

2021-06-09 20:29 UTC, whit1206 commented on translations.yaml
> +  application_invite: "{inviter_name} has invited you to an ATAT application"
change to "a cloud application"

2021-06-09 20:29 UTC, whit1206 commented on translations.yaml
> +  portfolio_invite: "{inviter_name} has invited you to an ATAT portfolio"
change to 'a cloud portfolio"

2021-06-09 20:29 UTC, whit1206 commented on translations.yaml
> +    message: "The TO number has already been entered for an ATAT task order #{to_number}. Please double-check the TO number you are entering. If you believe this is in error, please contact support@c
just remove "an ATAT"

2021-06-09 20:29 UTC, whit1206 commented on translations.yaml
> +  title_tag: Sign in | ATAT
remove "| ATAT"

2021-06-09 20:29 UTC, whit1206 commented on translations.yaml
> +  h1_title: Access ATAT
change to "Access Cloud"

2021-06-09 20:29 UTC, whit1206 commented on translations.yaml
> +    estimate_warning: Reports displayed in ATAT are estimates and not a system of record. To manage your costs, go to Azure by selecting the Login to Azure button above.
change first "Azure" to "the CSP" and change "Login to Azure" to "Login"

2021-06-09 20:29 UTC, whit1206 commented on uitests/framework/page_objects/__init__.py
> +                (By.CSS_SELECTOR, "div.home__content"), "ATAT Services"
Change all 'ATAT Services" to "Cloud Services" in all places it still exists. There is no such thing as ATAT services

2021-06-09 20:29 UTC, whit1206 commented on uitests/framework/test_cases/test_new_user.py
> +                    (By.CSS_SELECTOR, "div.home__content"), "ATAT Services"
Change to Cloud Services

2021-06-09 20:29 UTC, whit1206 commented on uitests/html/New_App_Step_3.html
> +<td>ATAT Services</td>
Change to "Cloud Services"

2021-06-09 20:29 UTC, whit1206 commented on uitests/html/New_Portfolio.html
> +<td>ATAT Services</td>
change

2021-06-14 15:50 UTC, danielgottlieb-ctr commented on README.md
> +- `CONTRACT_END_DATE`: String specifying the end date of the Cloud contract. Used for task order validation. Example: 2019-09-14
done

2021-06-14 15:54 UTC, danielgottlieb-ctr commented on templates/emails/application/invitation.txt
> +{{ owner }} has invited you to join a ATAT Application. Login now to view or use your ATAT resources.
all have been updated

2021-06-14 15:55 UTC, danielgottlieb-ctr commented on templates/emails/base.txt
> +ATAT is managed by the Cloud Computing Program Office. Learn more at atat.cloud.
done

2021-06-14 15:57 UTC, danielgottlieb-ctr commented on templates/emails/portfolio/invitation.txt
> +{{ owner }} has invited you to join a ATAT Portfolio.  Login now to view or use your ATAT resources.
done

2021-06-14 15:57 UTC, danielgottlieb-ctr commented on templates/emails/base.txt
> +ATAT is a DoD enterprise-wide solution for commercial cloud services.
updated

2021-06-14 15:59 UTC, danielgottlieb-ctr commented on translations.yaml
> +    estimate_warning: Reports displayed in ATAT are estimates and not a system of record. To manage your costs, go to Azure by selecting the Login to Azure button above.
Done

2021-06-14 15:59 UTC, danielgottlieb-ctr commented on uitests/framework/page_objects/__init__.py
> +                (By.CSS_SELECTOR, "div.home__content"), "ATAT Services"
Done

2021-06-14 16:00 UTC, danielgottlieb-ctr commented on uitests/framework/test_cases/test_new_user.py
> +                    (By.CSS_SELECTOR, "div.home__content"), "ATAT Services"
Done

2021-06-14 16:00 UTC, danielgottlieb-ctr commented on uitests/html/New_App_Step_3.html
> +<td>ATAT Services</td>
Done

2021-06-14 16:00 UTC, danielgottlieb-ctr commented on uitests/html/New_Portfolio.html
> +<td>ATAT Services</td>
done

2021-06-15 04:08 UTC, danielgottlieb-ctr commented on translations.yaml
> +    message: "The TO number has already been entered for an ATAT task order #{to_number}. Please double-check the TO number you are entering. If you believe this is in error, please contact support@c
done

2021-06-15 04:08 UTC, danielgottlieb-ctr commented on translations.yaml
> +  head: ATAT Services
done

2021-06-15 04:09 UTC, danielgottlieb-ctr commented on translations.yaml
> +  application_invite: "{inviter_name} has invited you to an ATAT application"
done

2021-06-15 04:09 UTC, danielgottlieb-ctr commented on translations.yaml
> +  portfolio_invite: "{inviter_name} has invited you to an ATAT portfolio"
done

2021-06-15 04:09 UTC, danielgottlieb-ctr commented on translations.yaml
> +  title_tag: Sign in | ATAT
done

2021-06-15 04:10 UTC, danielgottlieb-ctr commented on translations.yaml
> +  h1_title: Access ATAT
done

2021-06-21 18:53 UTC, kylelaker-ccpo commented
Seeing that #2439 has now been opened, I am going to close this PR.

2021-06-21 18:53 UTC, closed without merging