Feature/at 5886 User list view pagination
dod-ccpo/atat pull request #2417
Opened 2021-06-04 20:21 UTC by tonysumner-ccpo

AT-5886 User list view pagination

As a CCPO admin, I want the User List View to be paginated, so that I don’t have an endless scroll that takes a long time to load on the page.

This will be functionally equivalent to: AT-5851: Portfolio List View paginationTO DO 

See below for an image of the component, and see design specs on the Users List View page on Abstract. 

Note: Abstract/Invision links will only be available until June 2021. A PNG version of the view from the above Abstract link is retained for reference on Confluence here: Users List View.png. Please see Design Files and Assets  in Confluence for instructions on how you can view design specs using Sketch.

2021-06-07 20:42 UTC, tonysumner-ccpo commented on package.json
> +    "test:VueJScoverage": "jest --coverage --collectCoverageFrom='js/**/*.vue'",
to test Jest tests for a fully structured Vue component.  I added the first fully structured Vue component this week.

2021-06-10 19:52 UTC, jGonzalez-CCPO requested changes
how we can get this better?

3 Code Smells
86.0% 86.0% Coverage

2021-06-11 14:23 UTC, jGonzalez-CCPO requested changes
there is still coverage and smells pending:

Code Smell A 10 Code Smells
89.8% 89.8% Coverage

2021-06-11 15:36 UTC, jGonzalez-CCPO commented
love this stats: 

Bug A 0 Bugs
Vulnerability A 0 Vulnerabilities
Security Hotspot A 0 Security Hotspots
Code Smell A 0 Code Smells

94.0% 94.0% Coverage
0.0% 0.0% Duplication

2021-06-11 16:05 UTC, jGonzalez-CCPO requested changes

2021-06-11 16:39 UTC, jGonzalez-CCPO approved these changes

2021-06-11 17:59 UTC, merged

2021-06-11 20:50 UTC, jGonzalez-CCPO commented on atat/routes/admin/admin.py
> +    service_branches_description_json = json.dumps(service_branches_description)
if you want the list to be sorted: 

service_branches_description_json = json.dumps(service_branches_description).sort())

2021-06-11 20:51 UTC, jGonzalez-CCPO commented on atat/routes/admin/admin.py
> +    service_branches_description_json = json.dumps(service_branches_description)
but I think the order is the exact order requested by the DOD that is a custom order not alphabetic so Other is the last and the branches are in order of use.